(()=>{
const CORE='transporteMadeiraFiscalizacaoV3',DEC='transporteMadeiraDecisaoV3',OLDDEC='transporteMadeiraDecisaoV2',LEGAL='transporteMadeiraLegalBOv2';
const $=id=>document.getElementById(id);
function hasSaved(){try{const d=JSON.parse(localStorage.getItem(CORE)||'{}');return !!(d.exigeDof||d.sistema||d.volumeDeclarado||d.tipoMadeira||(d.measurements||[]).length||Object.values(d.checks||{}).some(Boolean))}catch(e){return false}}
function resetAll(){localStorage.removeItem(CORE);localStorage.removeItem(DEC);localStorage.removeItem(OLDDEC);localStorage.removeItem(LEGAL);location.reload()}
function startExperience(){const screen=$('screen-start');if(!screen)return;const card=screen.querySelector('.card');if(!card)return;let saved=hasSaved(),box=document.createElement('div');box.className='resume-box';box.innerHTML=saved?`<div class="notice info"><strong>Há uma fiscalização em andamento salva neste aparelho.</strong><p>Escolha conscientemente se deseja continuar ou começar outra ocorrência.</p><div class="btn-row"><button class="btn primary" id="resumeInspection">Continuar fiscalização</button><button class="btn danger" id="freshInspection">Começar nova fiscalização</button></div></div>`:`<div class="notice success"><strong>Nenhuma fiscalização anterior encontrada.</strong><p>Você pode iniciar um novo atendimento.</p></div>`;card.insertAdjacentElement('afterend',box);$('resumeInspection')?.addEventListener('click',()=>{const d=JSON.parse(localStorage.getItem(CORE)||'{}');let target=d.tipoMadeira?3:(d.exigeDof||d.sistema||d.volumeDeclarado)?1:0;if(typeof showStep==='function')showStep(target)});$('freshInspection')?.addEventListener('click',()=>{if(confirm('Começar uma nova fiscalização? Os dados salvos da ocorrência anterior serão apagados.'))resetAll()});$('newInspectionStart')?.addEventListener('click',()=>{if(confirm('Começar uma nova fiscalização? Os dados salvos da ocorrência anterior serão apagados.'))resetAll()});
}
function systemGuidance(){const sel=$('sistema');if(!sel)return;let box=$('systemAdaptiveHelp');if(!box){box=document.createElement('div');box.id='systemAdaptiveHelp';box.className='notice info';sel.closest('.card')?.appendChild(box)}const v=sel.value;if(v==='DOF+')box.innerHTML='<strong>DOF+ — o que conferir agora</strong><ul><li>Autenticidade e situação do documento.</li><li>Código de rastreio, quando aplicável, e sua correspondência com o produto/origem.</li><li>Produto, espécie, volume, origem, destino, veículo, rota e validade.</li><li>Compatibilidade entre DOF+, documento fiscal e carga física.</li></ul><small>O código de rastreio não é mero número de conferência: ele integra a rastreabilidade da origem do produto.</small>';else if(v==='DOF Legado')box.innerHTML='<strong>DOF Legado — o que conferir agora</strong><ul><li>Validade e autenticidade.</li><li>Produto, espécie, volume, origem e destino.</li><li>Veículo/placas e percurso.</li><li>Compatibilidade com documento fiscal e carga.</li></ul>';else if(v==='Sistema estadual integrado')box.innerHTML='<strong>Sistema estadual — atenção</strong><p>Confira a regra do sistema apresentado e sua integração/validade para o transporte. Não presuma que os mesmos campos do DOF+ se aplicam sem conferência.</p>';else if(v==='DOF+ e DOF Legado na mesma carga')box.innerHTML='<strong>Carga com documentos de sistemas distintos</strong><p>Trate cada documento e respectiva parcela da carga separadamente e depois confira a compatibilidade do conjunto.</p>';else if(v==='Nenhum')box.innerHTML='<strong>Nenhum documento apresentado</strong><p>Primeiro confirme se o produto está sujeito ao controle. Se estiver, esta informação alimentará diretamente o motor de decisão.</p>';else box.innerHTML='<strong>Selecione o sistema/documento apresentado.</strong><p>O aplicativo mostrará somente as conferências relevantes para essa situação.</p>'}
function productLanguage(){const sel=$('tipoMadeira');if(!sel)return;const label=sel.closest('.field')?.querySelector('label');if(label)label.textContent='O que você tem na sua frente?';const help=sel.closest('.field')?.querySelector('small');if(help)help.textContent='Escolha pela forma física da carga. O aplicativo seleciona e explica o método de cubagem correspondente.';const names={tora:'Toras / mourões', 'serrada-peca':'Madeira serrada — peças acessíveis para medir', 'serrada-carga':'Madeira serrada carregada no veículo',tabicada:'Madeira serrada empilhada com tabiques',lenha:'Lenha / material roliço empilhado',dormente:'Dormentes',carvao:'Carvão vegetal'};[...sel.options].forEach(o=>{if(names[o.value])o.textContent=names[o.value]})}
function groupingQuestion(){const form=$('measurementForm'),type=$('tipoMadeira')?.value;if(!form||!['serrada-peca','tora'].includes(type))return;if(form.querySelector('#groupingHelp'))return;const box=document.createElement('div');box.id='groupingHelp';box.className='notice info';box.innerHTML='<strong>As peças possuem as mesmas dimensões?</strong><div class="btn-row"><button type="button" class="btn secondary" data-group="yes">Sim, posso formar um grupo</button><button type="button" class="btn ghost" data-group="no">Não / há tamanhos diferentes</button></div><div id="groupingAnswer" class="calc-help"></div>';form.prepend(box);box.querySelector('[data-group="yes"]').onclick=()=>{$('groupingAnswer').innerHTML='<strong>Faça um grupo.</strong> Meça uma configuração, informe a quantidade de peças realmente iguais e adicione. Depois crie outro grupo se necessário.'};box.querySelector('[data-group="no"]').onclick=()=>{$('groupingAnswer').innerHTML='<strong>Divida a carga em grupos.</strong> Registre separadamente cada conjunto de dimensões. Não use uma medida única para peças diferentes.'}}
const QUICK={
 'Precisa de DOF?':'Primeiro identifique o produto e verifique se ele está sujeito ao controle de origem florestal ou se existe hipótese específica de dispensa. Não conclua pela aparência da carga. Use a etapa “Documentação e exigibilidade” e consulte a fonte oficial indicada no aplicativo.',
 'Como cubar?':'Na etapa “O que você tem na sua frente?”, escolha a forma física da carga. A tela seguinte mostra onde medir, quantas medições fazer, fórmula, unidade e memória do cálculo.',
 'O que conferir na rota?':'Confronte o percurso efetivamente constatado com o autorizado/declarado, além de validade, veículo/placas, eventual comboio e transbordo. Divergência deve ser registrada como fato objetivo.',
 'Quem pode ser responsabilizado?':'A responsabilidade deve ser individualizada conforme a participação. O GPO orienta verificar transportador e, quando cabível, emissor do DOF/contratante do frete. O aplicativo não presume responsabilidade automática.',
 'Diferença de 10%?':'Não trate 10% como tolerância universal de transporte. Cubagem técnica, divergência documental e regra de recebimento são questões distintas; confirme a norma aplicável ao fato.'
};
function quickConsult(){const btn=document.createElement('button');btn.id='quickConsultBtn';btn.className='quick-consult no-print';btn.textContent='? Dúvida rápida';document.body.appendChild(btn);const panel=document.createElement('div');panel.id='quickConsultPanel';panel.className='quick-panel hidden no-print';panel.innerHTML=`<div class="section-title"><h3>Consulta rápida</h3><button class="btn ghost mini" id="closeQuick">Fechar</button></div><p class="muted">Escolha uma dúvida. A consulta não altera os dados da fiscalização.</p><div class="quick-options">${Object.keys(QUICK).map(k=>`<button class="btn secondary" data-q="${k}">${k}</button>`).join('')}</div><div id="quickAnswer" class="notice info">Selecione um assunto.</div>`;document.body.appendChild(panel);btn.onclick=()=>panel.classList.toggle('hidden');$('closeQuick').onclick=()=>panel.classList.add('hidden');panel.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{$('quickAnswer').innerHTML=`<strong>${b.dataset.q}</strong><p>${QUICK[b.dataset.q]}</p>`})}
function hooks(){productLanguage();systemGuidance();$('sistema')?.addEventListener('change',systemGuidance);document.addEventListener('click',e=>{if(e.target?.id==='newInspection'){localStorage.removeItem(DEC)}},true);const obs=new MutationObserver(()=>groupingQuestion());if($('measurementForm'))obs.observe($('measurementForm'),{childList:true});$('tipoMadeira')?.addEventListener('change',()=>setTimeout(groupingQuestion,80));$('nextBtn')?.addEventListener('click',()=>setTimeout(groupingQuestion,80));groupingQuestion()}
document.addEventListener('DOMContentLoaded',()=>{startExperience();hooks();quickConsult()});
})();