const $=id=>document.getElementById(id),screens=['start','docs','route','product','measure','analysis','evidence','review'];let step=0;const STORAGE='transporteMadeiraFiscalizacaoV3',state={measurements:[],checks:{}};
const SOURCES={tora:'Manual IBAMA/2007 — madeira em tora: método geométrico, V = 0,7854 × dm² × L; mourões seguem o mesmo procedimento.',peca:'Manual IBAMA/2007 — madeira serrada nas diversas formas: V = espessura × largura × comprimento.',serrada:'Manual IBAMA/2007 — madeira serrada em veículo: volume aparente × 0,70; 30% correspondem aos espaços vazios.',tabicada:'Manual IBAMA/2007 — madeira serrada empilhada/tabicada: V = comprimento × largura × (altura − soma dos vãos/tabiques).',lenha:'Manual IBAMA/2007 — lenha/escoramento/estaca roliça/acha ou lasca: V = comprimento × largura × altura, em estéreo (st).',dormente:'Manual IBAMA/2007 — dormente: V = comprimento × largura × espessura; regra prática: média de três ou mais peças × quantidade.',carvao:'Manual IBAMA/2007 — carvão vegetal em veículo: V = comprimento × largura × altura, em mdc.'};
const source=k=>`<div class="legal"><strong>Referência técnica</strong><br>${SOURCES[k]}</div>`;
const checkStart=[['condutorOk','Condutor foi verificado'],['responsavelOk','Responsável / emitente da Nota Fiscal foi verificado'],['origemOk','Origem declarada foi verificada'],['destinoOk','Destino declarado foi verificado']];
const checkDocs=[['numeroDofOk','Número do DOF / documento foi verificado'],['notaFiscalOk','Número / dados da Nota Fiscal foram verificados'],['rastreioOk','Código de rastreio do DOF+ foi verificado, quando aplicável'],['dispensaOk','Hipótese de dispensa foi consultada/fundamentada, quando aplicável']];
const checkRoute=[['placas','Veículo e placas dos implementos foram verificados'],['validade','Início e fim da validade foram verificados'],['rota','Rota constante no documento foi confrontada com a rota constatada'],['comboio','Regras de comboio foram verificadas, quando aplicável'],['transbordo','Transbordo / mudança de veículo foi verificado, quando aplicável']];
const checkEvidence=[['fotoCarga','Carga foi documentada fotograficamente'],['fotoPlacas','Placas foram documentadas'],['fotoDocs','DOF/DOF+ e NF foram documentados'],['fotoMedicao','Medições foram documentadas'],['fotoProduto','Produto foi documentado']];
function renderChecklist(id,items){$(id).innerHTML=items.map(([k,t])=>`<label class="check-row"><input type="checkbox" data-check="${k}"><span><strong>${t}</strong></span></label>`).join('');$(id).querySelectorAll('[data-check]').forEach(x=>{x.checked=!!state.checks[x.dataset.check];x.onchange=()=>{state.checks[x.dataset.check]=x.checked;save()}})}
const val=id=>$(id)?.value||'',num=id=>parseFloat(val(id))||0,fmt=(n,d=3)=>Number(n||0).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
function desc(t){return ({tora:'Madeira em tora / mourão','serrada-peca':'Madeira serrada — peça a peça','serrada-carga':'Madeira serrada em carga/caminhão',tabicada:'Madeira serrada tabicada / empilhada',lenha:'Lenha / escoramento / estaca roliça / acha ou lasca',dormente:'Dormentes',carvao:'Carvão vegetal'})[t]||'Selecione o método'}
function collect(){return {exigeDof:val('exigeDof'),sistema:val('sistema'),volumeDeclarado:val('volumeDeclarado'),especiesDeclaradas:val('especiesDeclaradas'),tipoMadeira:val('tipoMadeira'),measurements:state.measurements,checks:state.checks}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(collect()));updateMetrics()}
function load(){try{let d=JSON.parse(localStorage.getItem(STORAGE)||'{}');state.measurements=d.measurements||[];state.checks=d.checks||{};['exigeDof','sistema','volumeDeclarado','especiesDeclaradas','tipoMadeira'].forEach(k=>{if($(k)&&d[k]!=null)$(k).value=d[k]})}catch(e){}}
function showStep(n){step=Math.max(0,Math.min(7,n));document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(`screen-${screens[step]}`).classList.add('active');$('progressFill').style.width=`${(step+1)*12.5}%`;$('progressLabel').textContent=`Etapa ${step+1} de 8`;$('prevBtn').disabled=!step;$('nextBtn').textContent=step===7?'Concluir':'Continuar';if(step===4)renderMeasurementForm();if(step===5)renderAnalysis();if(step===7)renderReview();scrollTo(0,0)}
function fields3(extra=''){return `<div class="grid-3"><div class="field"><label>Comprimento (m)</label><input id="mL" type="number" step=".01"></div><div class="field"><label>Largura (m)</label><input id="mW" type="number" step=".01"></div><div class="field"><label>Altura / espessura (m)</label><input id="mH" type="number" step=".001"></div>${extra}</div>`}
function renderMeasurementForm(){let t=val('tipoMadeira'),h='';$('methodBadge').textContent=desc(t);if(t==='tora')h=`<h3>Madeira em tora / mourão</h3><p>Informe as medidas da peça ou de um grupo de peças iguais.</p><div class="grid"><div class="field"><label>Diâmetro da base (cm)</label><input id="mD1" type="number" step="0.1"></div><div class="field"><label>Diâmetro do topo (cm)</label><input id="mD2" type="number" step="0.1"></div><div class="field"><label>Comprimento (m)</label><input id="mL" type="number" step="0.01"></div><div class="field"><label>Quantidade de peças iguais</label><input id="mQ" type="number" value="1" min="1"></div></div><div class="calc-help">O aplicativo calcula o diâmetro médio e aplica V = 0,7854 × dm² × comprimento × quantidade.</div>${source('tora')}<button class="btn primary" onclick="addMeasurement()">Calcular e adicionar</button>`;
else if(t==='serrada-peca')h=`<h3>Madeira serrada — peça a peça</h3>${fields3('<div class="field"><label>Quantidade de peças iguais</label><input id="mQ" type="number" value="1" min="1"></div>')}<div class="calc-help">V = espessura × largura × comprimento × quantidade.</div>${source('peca')}<button class="btn primary" onclick="addMeasurement()">Calcular e adicionar</button>`;
else if(t==='serrada-carga')h=`<h3>Madeira serrada em carga/caminhão</h3>${fields3()}<div class="calc-help">Volume real estimado = comprimento × largura × altura × 0,70.</div>${source('serrada')}<button class="btn primary" onclick="addMeasurement()">Calcular e adicionar</button>`;
else if(t==='tabicada')h=`<h3>Madeira serrada tabicada / empilhada</h3>${fields3('<div class="field"><label>Soma da espessura dos tabiques/vãos na altura (m)</label><input id="mGap" type="number" step=".001"></div>')}<div class="calc-help">V = comprimento × largura × (altura − soma dos tabiques/vãos).</div>${source('tabicada')}<button class="btn primary" onclick="addMeasurement()">Calcular e adicionar</button>`;
else if(t==='lenha')h=`<h3>Lenha / material roliço empilhado</h3>${fields3()}<div class="notice info">Resultado em estéreo (st). Não será somado automaticamente ao total em m³ sem conversão aplicável ao caso.</div>${source('lenha')}<button class="btn primary" onclick="addMeasurement()">Calcular e adicionar</button>`;
else if(t==='dormente')h=`<h3>Dormentes</h3>${fields3('<div class="field"><label>Quantidade de peças</label><input id="mQ" type="number" value="1" min="1"></div>')}<div class="calc-help">V = comprimento × largura × espessura × quantidade. Para amostragem, registre a média representativa conforme o Manual.</div>${source('dormente')}<button class="btn primary" onclick="addMeasurement()">Calcular e adicionar</button>`;
else if(t==='carvao')h=`<h3>Carvão vegetal</h3>${fields3()}<div class="notice info">Resultado em metro de carvão (mdc).</div>${source('carvao')}<button class="btn primary" onclick="addMeasurement()">Calcular e adicionar</button>`;
else h='<div class="notice info">Selecione o método de cubagem na etapa anterior.</div>';$('measurementForm').innerHTML=h;renderMeasurements()}
window.addMeasurement=()=>{let t=val('tipoMadeira'),n=id=>parseFloat($(id)?.value)||0,v=0,u='m³',formula='';if(t==='tora'){let d1=n('mD1')/100,d2=n('mD2')/100,L=n('mL'),q=Math.max(1,n('mQ')),dm=(d1+d2)/2;v=.7854*dm*dm*L*q;formula=`0,7854 × ${fmt(dm)}² × ${fmt(L,2)} × ${q}`}else if(t==='serrada-peca'||t==='dormente'){let L=n('mL'),w=n('mW'),h=n('mH'),q=Math.max(1,n('mQ'));v=L*w*h*q;formula=`${fmt(L,2)} × ${fmt(w,3)} × ${fmt(h,3)} × ${q}`}else if(t==='serrada-carga'){let L=n('mL'),w=n('mW'),h=n('mH');v=L*w*h*.70;formula=`${fmt(L,2)} × ${fmt(w,2)} × ${fmt(h,2)} × 0,70`}else if(t==='tabicada'){let L=n('mL'),w=n('mW'),h=n('mH'),g=n('mGap');v=L*w*Math.max(0,h-g);formula=`${fmt(L,2)} × ${fmt(w,2)} × (${fmt(h,2)} − ${fmt(g)})`}else if(t==='lenha'||t==='carvao'){v=n('mL')*n('mW')*n('mH');u=t==='lenha'?'st':'mdc';formula=`${fmt(n('mL'),2)} × ${fmt(n('mW'),2)} × ${fmt(n('mH'),2)}`}if(v<=0)return alert('Informe medidas válidas.');state.measurements.push({id:Date.now(),type:t,label:desc(t),volume:v,unit:u,formula});save();renderMeasurements()};
function renderMeasurements(){let el=$('measurementList');el.innerHTML=state.measurements.length?state.measurements.map((m,i)=>`<div class="measurement-item"><div class="measurement-item-head"><strong>${i+1}. ${m.label}</strong><button class="btn ghost mini no-print" onclick="removeMeasurement(${m.id})">Excluir</button></div><p>${m.formula}</p><strong>${fmt(m.volume)} ${m.unit}</strong></div>`).join(''):'<div class="muted">Nenhuma medição registrada.</div>';updateMetrics()}
window.removeMeasurement=id=>{state.measurements=state.measurements.filter(m=>m.id!==id);save();renderMeasurements()};const totalM3=()=>state.measurements.filter(m=>m.unit==='m³').reduce((a,b)=>a+b.volume,0);
function updateMetrics(){let m=totalM3(),d=num('volumeDeclarado'),dif=m-d,p=d?dif/d*100:null;if($('totalMeasured'))$('totalMeasured').textContent=`${fmt(m)} m³`;if($('declaredMetric'))$('declaredMetric').textContent=`${fmt(d)} m³`;if($('diffMetric'))$('diffMetric').textContent=`${dif>=0?'+':''}${fmt(dif)} m³`;if($('pctMetric'))$('pctMetric').textContent=p==null?'—':`${p>=0?'+':''}${fmt(p,2)}%`}
function renderAnalysis(){let m=totalM3(),d=num('volumeDeclarado'),dif=m-d,p=d?dif/d*100:null,cls='gray',title='Dados insuficientes',body='Informe o volume declarado e faça a cubagem.';if(d>0&&m>0){let a=Math.abs(p);if(a>10){cls='red';title='Diferença superior a 10%';body=`Documento: ${fmt(d)} m³. Cubagem: ${fmt(m)} m³. Diferença: ${dif>=0?'+':''}${fmt(dif)} m³ (${p>=0?'+':''}${fmt(p,2)}%). O percentual auxilia a análise e não substitui a regra normativa aplicável.`}else if(a>0){cls='yellow';title='Diferença de até 10%';body=`Documento: ${fmt(d)} m³. Cubagem: ${fmt(m)} m³. Diferença: ${dif>=0?'+':''}${fmt(dif)} m³ (${p>=0?'+':''}${fmt(p,2)}%). Não tratar 10% como tolerância universal de transporte.`}else{cls='green';title='Volumes coincidentes';body='A cubagem apurada coincide com o volume declarado.'}}$('analysisBadge').className=`status ${cls}`;$('analysisBadge').textContent=title;$('analysisBox').innerHTML=`<h3>${title}</h3><p>${body}</p><div class="notice info"><strong>Atenção:</strong> método/coeficiente de cubagem e tolerância documental são institutos diferentes.</div>`}
const status=k=>state.checks[k]?'Verificado':'Não registrado';function renderReview(){let d=collect(),m=totalM3(),decl=parseFloat(d.volumeDeclarado)||0,dif=m-decl,p=decl?dif/decl*100:null,all=[...checkStart,...checkDocs,...checkRoute,...checkEvidence],rows=all.map(x=>`<tr><th>${x[1]}</th><td>${status(x[0])}</td></tr>`).join(''),mr=state.measurements.map((x,i)=>`<tr><td>${i+1}</td><td>${x.label}</td><td>${x.formula}</td><td>${fmt(x.volume)} ${x.unit}</td></tr>`).join('')||'<tr><td colspan="4">Sem medições.</td></tr>';$('reviewContent').innerHTML=`<div class="card"><h3>Documentação</h3><p><strong>Sistema:</strong> ${d.sistema||'—'}<br><strong>Volume declarado:</strong> ${d.volumeDeclarado||'—'} m³<br><strong>Espécies declaradas:</strong> ${d.especiesDeclaradas||'—'}</p></div><div class="card"><h3>Método de cubagem</h3><p>${desc(d.tipoMadeira)}</p><table><thead><tr><th>#</th><th>Método</th><th>Memória</th><th>Resultado</th></tr></thead><tbody>${mr}</tbody></table></div><div class="card"><h3>Comparação</h3><p>Apurado: <strong>${fmt(m)} m³</strong> | Declarado: <strong>${fmt(decl)} m³</strong> | Diferença: <strong>${fmt(dif)} m³${p!==null?` (${fmt(p,2)}%)`:''}</strong></p></div><div class="card"><h3>Verificações</h3><table>${rows}</table></div>`}
function exportJson(){let blob=new Blob([JSON.stringify(collect(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fiscalizacao-transporte-madeira.json';a.click();URL.revokeObjectURL(a.href)}
function pdf(){if(!window.jspdf)return print();const {jsPDF}=window.jspdf,doc=new jsPDF(),d=collect();let y=18;doc.setFontSize(16);doc.text('Fiscalização — Transporte de Madeira',14,y);y+=10;doc.setFontSize(10);[`Método: ${desc(d.tipoMadeira)}`,`Volume declarado: ${d.volumeDeclarado||'—'} m³`,`Volume apurado: ${fmt(totalM3())} m³`].forEach(t=>{doc.text(t,14,y);y+=7});state.measurements.forEach((m,i)=>{let lines=doc.splitTextToSize(`${i+1}. ${m.label}: ${m.formula} = ${fmt(m.volume)} ${m.unit}`,180);doc.text(lines,14,y);y+=lines.length*5+3});doc.save('relatorio-fiscalizacao-madeira.pdf')}
function init(){load();renderChecklist('checkStart',checkStart);renderChecklist('checkDocs',checkDocs);renderChecklist('checkRoute',checkRoute);renderChecklist('checkEvidence',checkEvidence);['exigeDof','sistema','volumeDeclarado','especiesDeclaradas','tipoMadeira'].forEach(id=>{if($(id))$(id).onchange=save});$('prevBtn').onclick=()=>showStep(step-1);$('nextBtn').onclick=()=>step<7?showStep(step+1):renderReview();$('clearMeasures').onclick=()=>{if(confirm('Limpar todas as medições?')){state.measurements=[];save();renderMeasurements()}};$('exportJson').onclick=exportJson;$('printReport').onclick=()=>print();$('downloadPdf').onclick=pdf;$('newInspection').onclick=()=>{if(confirm('Iniciar nova fiscalização e limpar os dados locais?')){localStorage.removeItem(STORAGE);localStorage.removeItem('transporteMadeiraDecisaoV2');localStorage.removeItem('transporteMadeiraLegalBOv2');location.reload()}};showStep(0)}
document.addEventListener('DOMContentLoaded',init);