const $=id=>document.getElementById(id);
const screens=['start','docs','route','product','measure','analysis','evidence','review'];
let step=0;
const STORAGE='transporteMadeiraFiscalizacaoV1';
const state={measurements:[],checks:{}};

const SOURCES={
  dofObrigatorio:{title:'DOF — licença obrigatória',ref:'Lei 12.651/2012, art. 36; IN IBAMA 21/2014; GPO 5.6.8',url:'https://www.gov.br/ibama/pt-br/assuntos/biodiversidade/flora-e-madeira/documento-de-origem-florestal-dof'},
  dofMais:{title:'DOF+ Rastreabilidade',ref:'IN IBAMA 16/2022, art. 1º e Anexo II',url:'https://www.gov.br/ibama/pt-br/assuntos/biodiversidade/flora-e-madeira/documento-de-origem-florestal-dof/dof-rastreabilidade'},
  veiculoRota:{title:'Veículo, placas e rota',ref:'GPO 5.6.10.1; IN IBAMA 21/2014 (transporte)',url:'https://www.ibama.gov.br/component/legislacao/?legislacao=134547&view=legislacao'},
  comboio:{title:'Comboio',ref:'GPO 5.6.10.2',url:''},
  transbordo:{title:'Transbordo / modalidades',ref:'GPO 5.6.10.6 e 5.6.10.7',url:''},
  validade:{title:'Validade do documento',ref:'GPO 5.6.10.8 e 5.6.10.9.4',url:''},
  invalidade:{title:'Hipóteses de invalidade',ref:'GPO 5.6.10.9.1 a 5.6.10.9.6',url:''},
  volume10:{title:'Divergência volumétrica no recebimento',ref:'IN IBAMA 21/2014, art. 53',url:'https://www.ibama.gov.br/component/legislacao/?legislacao=134547&view=legislacao'},
  cubagemTora:{title:'Cubagem de tora — método geométrico',ref:'Manual de Fiscalização IBAMA/2007, cap. 3, item 1.1',url:''},
  cubagemSerrada:{title:'Madeira serrada — peça',ref:'Manual de Fiscalização IBAMA/2007, cap. 3, item 1.2.1',url:''},
  cubagemCaminhao:{title:'Madeira serrada em caminhão — coeficiente 70%',ref:'Manual de Fiscalização IBAMA/2007, cap. 3, item 1.2.2',url:''},
  cubagemTabicada:{title:'Madeira tabicada / empilhada',ref:'Manual de Fiscalização IBAMA/2007, cap. 3, item 1.2.3',url:''},
  coeficientes:{title:'Coeficientes técnicos por apresentação',ref:'Manual de Fiscalização IBAMA/2007, Anexo/Tabela de cubagem: pranchões 6%, vigas 15%, caibros 12%, tábuas 14%, ripas 16%, faqueados 40%, laminados 23%, aproveitamentos 17%',url:''},
  crv:{title:'Coeficientes de rendimento volumétrico',ref:'Resolução CONAMA 411/2009, compilada com alterações; IN IBAMA 21/2014',url:'https://www.gov.br/ibama/pt-br/assuntos/biodiversidade/flora-e-madeira/documento-de-origem-florestal-dof'},
};

const checkDocs=[
 ['docAcompanha','Documento de controle acompanha a carga','Confirmar a existência e a correspondência do documento com a carga transportada.','dofObrigatorio'],
 ['nfConfere','Nota Fiscal foi conferida com o documento florestal','Comparar emitente, destinatário, produto, espécie e volume.','dofObrigatorio'],
 ['origemDestino','Origem e destino conferem','Confrontar documento, NF e declaração do condutor.','dofObrigatorio'],
 ['rastreio','Código de rastreio foi conferido quando aplicável','No DOF+, registrar e conferir o código de rastreio/origem do crédito.','dofMais'],
 ['dispensa','Eventual dispensa de DOF foi fundamentada','Se não exigir DOF, registrar a hipótese concreta e o documento que comprova a origem.','dofObrigatorio']
];
const checkRoute=[
 ['placas','Placas do veículo e implementos conferem','Confrontar todos os registros físicos com o documento.','veiculoRota'],
 ['rota','Rota da abordagem é compatível com a rota declarada','Registrar a rota constante do documento e a rota efetivamente informada/constatada.','veiculoRota'],
 ['validade','Transporte está dentro do período de validade','Verificar início e fim; tráfego anterior ao início ou após o término exige análise.','validade'],
 ['comboio','Regras de comboio foram verificadas, se aplicável','Em comboio, verificar documento específico para cada unidade conforme GPO.','comboio'],
 ['transbordo','Transbordo / mudança de veículo foi verificado, se aplicável','Conferir modalidades, placas/registros e itinerário de cada trecho.','transbordo']
];
const checkEvidence=[
 ['fotoFrontal','Foto frontal da carga','Registrar visão geral da carga.'],['fotoTraseira','Foto traseira da carga','Registrar a disposição e amarração.'],['fotoLaterais','Fotos laterais','Registrar ambos os lados quando possível.'],['fotoPlacas','Fotos das placas','Veículo trator e implementos.'],['fotoDocs','Documentos registrados','DOF/DOF+, NF e outros documentos pertinentes.'],['fotoMedicao','Medições documentadas','Fotografar trena/paquímetro e pontos de medição quando possível.'],['fotoProduto','Produto e espécie documentados','Registrar características relevantes das peças/toras.'],['localizacao','Local/rota documentados','Registrar referência do ponto da abordagem.']
];

function sourceHtml(key){const s=SOURCES[key];if(!s)return'';return `<div class="legal"><strong>${s.title}</strong><br>${s.ref}${s.url?` · <a href="${s.url}" target="_blank" rel="noopener">fonte oficial</a>`:''}</div>`}
function renderChecklist(containerId,items){const el=$(containerId);el.innerHTML=items.map(([id,title,desc,src])=>`<label class="check-row"><input type="checkbox" data-check="${id}"><span><strong>${title}</strong><small>${desc}</small>${src?sourceHtml(src):''}</span></label>`).join('');el.querySelectorAll('[data-check]').forEach(cb=>{cb.checked=!!state.checks[cb.dataset.check];cb.addEventListener('change',()=>{state.checks[cb.dataset.check]=cb.checked;save();});});}
function showStep(n){step=Math.max(0,Math.min(screens.length-1,n));document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(`screen-${screens[step]}`).classList.add('active');$('progressFill').style.width=`${((step+1)/screens.length)*100}%`;$('progressLabel').textContent=`Etapa ${step+1} de ${screens.length}`;$('prevBtn').disabled=step===0;$('nextBtn').textContent=step===screens.length-1?'Concluir':'Continuar';if(screens[step]==='measure')renderMeasurementForm();if(screens[step]==='analysis')renderAnalysis();if(screens[step]==='review')renderReview();window.scrollTo({top:0,behavior:'smooth'});}

function val(id){return $(id)?.value||''} function num(id){return parseFloat(val(id))||0}
function fmt(n,d=3){return Number(n||0).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d})}
function collect(){const ids=['dataHora','local','equipe','bo','placa','implementos','condutor','responsavel','origem','destino','exigeDof','sistema','numeroDof','notaFiscal','volumeDeclarado','especiesDeclaradas','produtoDeclarado','codigoRastreio','validadeInicio','validadeFim','rotaDocumento','rotaConstatada','tipoMadeira','especiesEncontradas','produtoObs','divProduto','naturezaDivergencia','obsAnalise','providencias','conclusao'];const data={};ids.forEach(id=>data[id]=val(id));data.measurements=state.measurements;data.checks=state.checks;return data;}
function save(){localStorage.setItem(STORAGE,JSON.stringify(collect()));updateMetrics();}
function load(){const raw=localStorage.getItem(STORAGE);if(!raw)return;try{const d=JSON.parse(raw);Object.entries(d).forEach(([k,v])=>{if(k==='measurements')state.measurements=Array.isArray(v)?v:[];else if(k==='checks')state.checks=v||{};else if($(k))$(k).value=v??'';});}catch(e){console.warn(e)}}
function attachAutoSave(){document.querySelectorAll('input,select,textarea').forEach(el=>el.addEventListener('input',save));}

const deductions={pranchao:.06,viga:.15,caibro:.12,tabua:.14,ripa:.16,faqueado:.40,laminado:.23,aproveitamento:.17};
function measurementDescription(type){return ({tora:'Tora / mourão — método geométrico', 'serrada-peca':'Madeira serrada — peça por peça','serrada-carga':'Madeira serrada em veículo — 70% do volume aparente',tabicada:'Madeira serrada tabicada — descontar tabiques',pranchao:'Pranchões — dedução técnica 6%',viga:'Vigas — dedução técnica 15%',caibro:'Caibros — dedução técnica 12%',tabua:'Tábuas — dedução técnica 14%',ripa:'Ripas — dedução técnica 16%',faqueado:'Faqueados — dedução técnica 40%',laminado:'Laminados — dedução técnica 23%',aproveitamento:'Aproveitamentos — dedução técnica 17%',lenha:'Lenha / material roliço empilhado — estéreo e conversão',outro:'Outro — informar volume apurado manualmente'})[type]||'Selecione o produto';}

function renderMeasurementForm(){const type=val('tipoMadeira');$('methodBadge').textContent=measurementDescription(type);let html='';
 if(type==='tora')html=`<h3>Adicionar tora / mourão</h3><div class="grid-3"><div class="field"><label>Diâmetro base 1 (cm)</label><input id="mD1" type="number" step="0.1"></div><div class="field"><label>Diâmetro topo 1 (cm)</label><input id="mD2" type="number" step="0.1"></div><div class="field"><label>Comprimento (m)</label><input id="mL" type="number" step="0.01"></div><div class="field"><label>Diâmetro base 2 (cm) — opcional para irregular</label><input id="mD3" type="number" step="0.1"></div><div class="field"><label>Diâmetro topo 2 (cm) — opcional para irregular</label><input id="mD4" type="number" step="0.1"></div><div class="field"><label>Quantidade igual</label><input id="mQ" type="number" value="1" min="1"></div></div><div class="calc-help">Regular: dm=(base+topo)/2. Irregular: se quatro diâmetros forem informados, dm=(d1+d2+d3+d4)/4. V=0,7854×dm²×comprimento.</div>${sourceHtml('cubagemTora')}<div class="btn-row"><button class="btn primary" onclick="addMeasurement()">Adicionar medição</button></div>`;
 else if(type==='serrada-peca')html=`<h3>Adicionar lote de peças</h3><div class="grid"><div class="field"><label>Espessura (cm)</label><input id="mE" type="number" step="0.1"></div><div class="field"><label>Largura (cm)</label><input id="mW" type="number" step="0.1"></div><div class="field"><label>Comprimento (m)</label><input id="mL" type="number" step="0.01"></div><div class="field"><label>Quantidade de peças</label><input id="mQ" type="number" value="1" min="1"></div></div><div class="calc-help">V=espessura×largura×comprimento×quantidade (todas as medidas convertidas para metros).</div>${sourceHtml('cubagemSerrada')}<div class="btn-row"><button class="btn primary" onclick="addMeasurement()">Adicionar lote</button></div>`;
 else if(type==='serrada-carga')html=`<h3>Medir bloco aparente da carga</h3><div class="grid-3"><div class="field"><label>Comprimento (m)</label><input id="mL" type="number" step="0.01"></div><div class="field"><label>Largura (m)</label><input id="mW" type="number" step="0.01"></div><div class="field"><label>Altura (m)</label><input id="mH" type="number" step="0.01"></div></div><div class="calc-help">Volume real estimado = comprimento × largura × altura × 0,70. O Manual/2007 atribui 30% aos espaços vazios entre peças.</div>${sourceHtml('cubagemCaminhao')}<div class="notice">Parâmetro técnico do Manual IBAMA/2007. Antes de usar como fundamento exclusivo, confira eventual coeficiente regional ou norma vigente específica.</div><div class="btn-row"><button class="btn primary" onclick="addMeasurement()">Adicionar bloco</button></div>`;
 else if(type==='tabicada')html=`<h3>Medir pilha tabicada</h3><div class="grid"><div class="field"><label>Comprimento (m)</label><input id="mL" type="number" step="0.01"></div><div class="field"><label>Largura (m)</label><input id="mW" type="number" step="0.01"></div><div class="field"><label>Altura total (m)</label><input id="mH" type="number" step="0.01"></div><div class="field"><label>Soma dos espaços/tabiques na altura (m)</label><input id="mGap" type="number" step="0.001"></div></div><div class="calc-help">V = comprimento × largura × (altura − soma das espessuras dos vãos/tabiques).</div>${sourceHtml('cubagemTabicada')}<div class="btn-row"><button class="btn primary" onclick="addMeasurement()">Adicionar pilha</button></div>`;
 else if(deductions[type]!==undefined){const p=deductions[type]*100;html=`<h3>${measurementDescription(type)}</h3><div class="grid-3"><div class="field"><label>Comprimento do bloco (m)</label><input id="mL" type="number" step="0.01"></div><div class="field"><label>Largura do bloco (m)</label><input id="mW" type="number" step="0.01"></div><div class="field"><label>Altura do bloco (m)</label><input id="mH" type="number" step="0.01"></div></div><div class="calc-help">Volume corrigido = volume externo × ${(1-deductions[type]).toFixed(2)} (dedução ${p}%).</div>${sourceHtml('coeficientes')}<div class="notice">O próprio Manual informa que esses coeficientes podem ser usados quando não houver coeficientes disponíveis na região. Trate-os como referência técnica subsidiária.</div><div class="btn-row"><button class="btn primary" onclick="addMeasurement()">Adicionar bloco</button></div>`;}
 else if(type==='lenha')html=`<h3>Lenha / material empilhado</h3><div class="grid"><div class="field"><label>Comprimento da pilha (m)</label><input id="mL" type="number" step="0.01"></div><div class="field"><label>Largura (m)</label><input id="mW" type="number" step="0.01"></div><div class="field"><label>Altura (m)</label><input id="mH" type="number" step="0.01"></div><div class="field"><label>Fator st por m³</label><select id="mFactor"><option value="">Manter em st / não converter</option><option value="1.5">Amazônia Legal — 1 m³ = 1,50 st</option><option value="1.2">Eucalipto — 1 m³ = 1,20 st</option><option value="2">Cerrado — 1 m³ = 2,00 st</option></select></div></div><div class="calc-help">Volume empilhado = C×L×A, em estéreo (st). Se selecionado fator histórico do Manual/2007, a aplicação converte para m³.</div><div class="notice">Confirme a adequação do fator ao caso concreto e à regulamentação vigente antes de utilizar a conversão.</div><div class="btn-row"><button class="btn primary" onclick="addMeasurement()">Adicionar pilha</button></div>`;
 else if(type==='outro')html=`<h3>Volume apurado por outro método</h3><div class="grid"><div class="field"><label>Descrição do método</label><input id="mMethod"></div><div class="field"><label>Volume apurado (m³)</label><input id="mManual" type="number" step="0.001"></div></div><div class="btn-row"><button class="btn primary" onclick="addMeasurement()">Adicionar resultado</button></div>`;
 else html=`<div class="notice info">Volte à etapa anterior e selecione o tipo de produto encontrado para carregar o método de mensuração correspondente.</div>`;
 $('measurementForm').innerHTML=html;renderMeasurements();}

window.addMeasurement=function(){const type=val('tipoMadeira');let volume=0,desc='',unit='m³';const n=id=>parseFloat($(id)?.value)||0;
 if(type==='tora'){const d1=n('mD1')/100,d2=n('mD2')/100,d3=n('mD3')/100,d4=n('mD4')/100,L=n('mL'),q=Math.max(1,n('mQ'));const dm=(d3&&d4)?(d1+d2+d3+d4)/4:(d1+d2)/2;volume=.7854*dm*dm*L*q;desc=`dm ${fmt(dm,3)} m × ${fmt(L,2)} m × ${q} un.`;}
 else if(type==='serrada-peca'){const e=n('mE')/100,w=n('mW')/100,L=n('mL'),q=Math.max(1,n('mQ'));volume=e*w*L*q;desc=`${fmt(e,3)} × ${fmt(w,3)} × ${fmt(L,2)} m × ${q} peças`;}
 else if(type==='serrada-carga'){const L=n('mL'),w=n('mW'),h=n('mH');volume=L*w*h*.70;desc=`${fmt(L,2)} × ${fmt(w,2)} × ${fmt(h,2)} × 0,70`;}
 else if(type==='tabicada'){const L=n('mL'),w=n('mW'),h=n('mH'),gap=n('mGap');volume=L*w*Math.max(0,h-gap);desc=`${fmt(L,2)} × ${fmt(w,2)} × (${fmt(h,2)} − ${fmt(gap,3)})`;}
 else if(deductions[type]!==undefined){const L=n('mL'),w=n('mW'),h=n('mH'),factor=1-deductions[type];volume=L*w*h*factor;desc=`${fmt(L,2)} × ${fmt(w,2)} × ${fmt(h,2)} × ${factor.toFixed(2)}`;}
 else if(type==='lenha'){const L=n('mL'),w=n('mW'),h=n('mH'),st=L*w*h,f=parseFloat($('mFactor')?.value)||0;if(f){volume=st/f;desc=`${fmt(st)} st ÷ ${f.toFixed(2)} = ${fmt(volume)} m³`;}else{volume=st;unit='st';desc=`${fmt(L,2)} × ${fmt(w,2)} × ${fmt(h,2)} = ${fmt(st)} st`;}}
 else if(type==='outro'){volume=n('mManual');desc=$('mMethod')?.value||'Método informado pelo agente';}
 if(volume<=0)return alert('Informe medidas válidas.');state.measurements.push({id:Date.now(),type,label:measurementDescription(type),volume,unit,desc});save();renderMeasurements();}
function renderMeasurements(){const list=$('measurementList');if(!list)return;if(!state.measurements.length)list.innerHTML='<div class="muted">Nenhuma medição registrada.</div>';else list.innerHTML=state.measurements.map((m,i)=>`<div class="measurement-item"><div class="measurement-item-head"><strong>${i+1}. ${m.label}</strong><button class="btn ghost mini no-print" onclick="removeMeasurement(${m.id})">Excluir</button></div><p>${m.desc}</p><p><strong>${fmt(m.volume)} ${m.unit}</strong></p></div>`).join('');updateMetrics();}
window.removeMeasurement=id=>{state.measurements=state.measurements.filter(m=>m.id!==id);save();renderMeasurements();};
function totalM3(){return state.measurements.filter(m=>m.unit==='m³').reduce((s,m)=>s+m.volume,0)}
function updateMetrics(){const measured=totalM3(),declared=num('volumeDeclarado'),diff=measured-declared,pct=declared?diff/declared*100:null;if($('totalMeasured'))$('totalMeasured').textContent=`${fmt(measured)} m³`;if($('declaredMetric'))$('declaredMetric').textContent=`${fmt(declared)} m³`;if($('diffMetric'))$('diffMetric').textContent=`${diff>=0?'+':''}${fmt(diff)} m³`;if($('pctMetric'))$('pctMetric').textContent=pct===null?'—':`${pct>=0?'+':''}${fmt(pct,2)}%`;}

function renderAnalysis(){const measured=totalM3(),declared=num('volumeDeclarado'),diff=measured-declared,pct=declared?diff/declared*100:null;let cls='gray',title='Dados insuficientes',body='Informe o volume documental e realize a mensuração para a comparação automática.';
 if(declared>0&&measured>0){const ap=Math.abs(pct);if(ap>10){cls='red';title='Divergência volumétrica superior a 10%';body=`Volume declarado: ${fmt(declared)} m³. Volume físico apurado: ${fmt(measured)} m³. Diferença: ${diff>=0?'+':''}${fmt(diff)} m³ (${pct>=0?'+':''}${fmt(pct,2)}%). O art. 53 da IN IBAMA 21/2014 trata da divergência superior a 10% no recebimento da carga. Durante o transporte, a incompatibilidade entre quantidade/volume e documento também deve ser analisada à luz do GPO 5.6.10.9.1 e demais circunstâncias. Não conclua automaticamente apenas pelo percentual.`;}else if(ap>0){cls='yellow';title='Divergência volumétrica até 10%';body=`Diferença calculada: ${diff>=0?'+':''}${fmt(diff)} m³ (${pct>=0?'+':''}${fmt(pct,2)}%). O parágrafo único do art. 53 da IN 21/2014 prevê ajuste administrativo para divergência menor que 10% no contexto do recebimento. Isso não transforma 10% em franquia universal de transporte: verifique produto, espécie, método de cubagem, GPO e situação concreta.`;}else{cls='green';title='Volumes coincidentes';body='O volume físico apurado coincide com o volume informado. Ainda assim, a regularidade depende das demais conferências: espécie, produto, veículo, rota, validade, origem, destino e autenticidade documental.';}}
 $('analysisBadge').className=`status ${cls}`;$('analysisBadge').textContent=title;$('analysisBox').innerHTML=`<h3>${title}</h3><p>${body}</p>${sourceHtml('volume10')}${sourceHtml('invalidade')}<div class="notice info" style="margin-top:12px"><strong>Regra de segurança jurídica:</strong> coeficiente de cubagem, espaços vazios, tolerância documental e CRV são conceitos diferentes. O sistema apresenta o cálculo; o agente define o enquadramento após conferir a norma aplicável.</div>`;}

function statusFor(key){return state.checks[key]?'Sim':'Não registrado'}
function renderReview(){const d=collect(),measured=totalM3(),declared=parseFloat(d.volumeDeclarado)||0,diff=measured-declared,pct=declared?diff/declared*100:null;const mrows=state.measurements.map((m,i)=>`<tr><td>${i+1}</td><td>${m.label}</td><td>${m.desc}</td><td>${fmt(m.volume)} ${m.unit}</td></tr>`).join('')||'<tr><td colspan="4">Sem medições</td></tr>';
 const checks=[...checkDocs,...checkRoute,...checkEvidence].map(x=>`<tr><th>${x[1]}</th><td>${statusFor(x[0])}</td></tr>`).join('');
 $('reviewContent').innerHTML=`<div class="card"><h3>Identificação</h3><table class="summary-table"><tr><th>Data/hora</th><td>${esc(d.dataHora)}</td></tr><tr><th>Local</th><td>${esc(d.local)}</td></tr><tr><th>Equipe</th><td>${esc(d.equipe)}</td></tr><tr><th>BO/PAmb</th><td>${esc(d.bo)}</td></tr><tr><th>Veículo</th><td>${esc(d.placa)} ${d.implementos?`/ ${esc(d.implementos)}`:''}</td></tr><tr><th>Condutor</th><td>${esc(d.condutor)}</td></tr><tr><th>Origem → destino</th><td>${esc(d.origem)} → ${esc(d.destino)}</td></tr></table></div>
 <div class="card"><h3>Documentação e carga</h3><table class="summary-table"><tr><th>Sistema</th><td>${esc(d.sistema)}</td></tr><tr><th>DOF/documento</th><td>${esc(d.numeroDof)}</td></tr><tr><th>NF</th><td>${esc(d.notaFiscal)}</td></tr><tr><th>Código de rastreio</th><td>${esc(d.codigoRastreio)}</td></tr><tr><th>Produto declarado</th><td>${esc(d.produtoDeclarado)}</td></tr><tr><th>Espécies declaradas</th><td>${esc(d.especiesDeclaradas)}</td></tr><tr><th>Produto encontrado</th><td>${esc(measurementDescription(d.tipoMadeira))}</td></tr><tr><th>Espécies encontradas</th><td>${esc(d.especiesEncontradas)}</td></tr></table></div>
 <div class="card"><h3>Mensuração</h3><table class="summary-table"><thead><tr><th>#</th><th>Tipo</th><th>Cálculo</th><th>Resultado</th></tr></thead><tbody>${mrows}</tbody></table><div class="metric-grid" style="margin-top:14px"><div class="metric"><span>Declarado</span><strong>${fmt(declared)} m³</strong></div><div class="metric"><span>Apurado</span><strong>${fmt(measured)} m³</strong></div><div class="metric"><span>Diferença</span><strong>${diff>=0?'+':''}${fmt(diff)} m³</strong></div><div class="metric"><span>Percentual</span><strong>${pct===null?'—':`${pct>=0?'+':''}${fmt(pct,2)}%`}</strong></div></div></div>
 <div class="card"><h3>Checklist registrado</h3><table class="summary-table">${checks}</table></div>
 <div class="card"><h3>Rota e validade</h3><table class="summary-table"><tr><th>Validade</th><td>${esc(d.validadeInicio)} a ${esc(d.validadeFim)}</td></tr><tr><th>Rota documental</th><td>${nl(esc(d.rotaDocumento))}</td></tr><tr><th>Rota constatada</th><td>${nl(esc(d.rotaConstatada))}</td></tr></table></div>
 <div class="card"><h3>Providências e conclusão do agente</h3><p><strong>Providências:</strong><br>${nl(esc(d.providencias))||'Não informado.'}</p><p><strong>Conclusão técnica do agente:</strong><br>${nl(esc(d.conclusao))||'Não informado.'}</p><p><strong>Observações da análise:</strong><br>${nl(esc(d.obsAnalise))||'Não informado.'}</p></div>
 <div class="card"><h3>Fundamentação utilizada pelo aplicativo</h3><div class="source-list">${Object.values(SOURCES).map(s=>`<div class="source-item"><strong>${s.title}</strong><small>${s.ref}</small></div>`).join('')}</div><div class="notice" style="margin-top:12px">Manual de Fiscalização IBAMA/2007: referência técnica histórica para métodos de mensuração. Coeficientes e regras jurídicas devem ser confrontados com a regulamentação vigente e com eventual disciplina regional específica.</div></div>`;}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function nl(s){return s.replace(/\n/g,'<br>')}

function reportText(){const d=collect(),measured=totalM3(),declared=parseFloat(d.volumeDeclarado)||0,diff=measured-declared,pct=declared?diff/declared*100:null;const lines=[];lines.push('RELATÓRIO TÉCNICO — FISCALIZAÇÃO DE TRANSPORTE DE PRODUTO FLORESTAL','');lines.push(`Data/hora: ${d.dataHora||'-'}`,`Local: ${d.local||'-'}`,`Equipe: ${d.equipe||'-'}`,`BO/PAmb: ${d.bo||'-'}`,`Veículo: ${d.placa||'-'} | Implementos: ${d.implementos||'-'}`,`Condutor: ${d.condutor||'-'}`,`Responsável/emitente: ${d.responsavel||'-'}`,`Origem: ${d.origem||'-'}`,`Destino: ${d.destino||'-'}`,'');lines.push('DOCUMENTAÇÃO',`Sistema: ${d.sistema||'-'}`,`DOF/documento: ${d.numeroDof||'-'}`,`Nota Fiscal: ${d.notaFiscal||'-'}`,`Código de rastreio: ${d.codigoRastreio||'-'}`,`Produto declarado: ${d.produtoDeclarado||'-'}`,`Espécies declaradas: ${d.especiesDeclaradas||'-'}`,'');lines.push('MENSURAÇÃO');state.measurements.forEach((m,i)=>lines.push(`${i+1}. ${m.label}: ${m.desc} = ${fmt(m.volume)} ${m.unit}`));lines.push(`Volume declarado: ${fmt(declared)} m³`,`Volume físico apurado: ${fmt(measured)} m³`,`Diferença: ${diff>=0?'+':''}${fmt(diff)} m³`, `Diferença percentual: ${pct===null?'não calculada':`${pct>=0?'+':''}${fmt(pct,2)}%`}`,'');lines.push('ROTA E VALIDADE',`Validade: ${d.validadeInicio||'-'} a ${d.validadeFim||'-'}`,`Rota documental: ${d.rotaDocumento||'-'}`,`Rota constatada: ${d.rotaConstatada||'-'}`,'');lines.push('PROVIDÊNCIAS',d.providencias||'Não informado.','','CONCLUSÃO TÉCNICA DO AGENTE',d.conclusao||'Não informado.','','FUNDAMENTAÇÃO / REFERÊNCIAS');Object.values(SOURCES).forEach(s=>lines.push(`• ${s.title}: ${s.ref}`));lines.push('','OBSERVAÇÃO: o aplicativo organiza dados e parâmetros técnicos. A decisão administrativa e o enquadramento permanecem sob responsabilidade do agente, considerada a norma vigente e a situação concreta.');return lines.join('\n');}
function downloadPDF(){const text=reportText();if(window.jspdf?.jsPDF){const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a4'});doc.setFont('helvetica');doc.setFontSize(10);const margin=14,width=182;const chunks=doc.splitTextToSize(text,width);let y=16;chunks.forEach(line=>{if(y>282){doc.addPage();y=16}doc.text(line,margin,y);y+=5});doc.save(`fiscalizacao-transporte-madeira-${new Date().toISOString().slice(0,10)}.pdf`);}else{alert('Gerador PDF indisponível no momento. Use “Imprimir / salvar como PDF”.');window.print();}}
function exportJson(){const blob=new Blob([JSON.stringify(collect(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`fiscalizacao-madeira-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href)}

$('prevBtn').addEventListener('click',()=>showStep(step-1));$('nextBtn').addEventListener('click',()=>{save();showStep(step+1)});$('clearMeasures').addEventListener('click',()=>{if(confirm('Limpar todas as medições?')){state.measurements=[];save();renderMeasurements()}});$('downloadPdf').addEventListener('click',downloadPDF);$('printReport').addEventListener('click',()=>window.print());$('exportJson').addEventListener('click',exportJson);$('newInspection').addEventListener('click',()=>{if(confirm('Iniciar nova fiscalização e apagar os dados salvos neste aparelho?')){localStorage.removeItem(STORAGE);location.reload()}});$('tipoMadeira').addEventListener('change',()=>{save();if(step===4)renderMeasurementForm()});

load();renderChecklist('checkDocs',checkDocs);renderChecklist('checkRoute',checkRoute);renderChecklist('checkEvidence',checkEvidence);attachAutoSave();if(!$('dataHora').value){const dt=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);$('dataHora').value=dt;save()}updateMetrics();showStep(0);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.warn));
