(()=>{
const METHODS={
 'Madeira em tora / mourão':{formula:'V = 0,7854 × dm² × L × quantidade',coef:'0,7854 = π/4',steps:['Meça o diâmetro da base da peça, em centímetros.','Meça o diâmetro do topo, em centímetros.','O aplicativo transforma os dois diâmetros para metros.','O aplicativo calcula a média: dm = (diâmetro da base + diâmetro do topo) ÷ 2.','Depois eleva essa média ao quadrado, multiplica por 0,7854, pelo comprimento e pela quantidade de peças iguais.'],example:'Exemplo: base 40 cm e topo 30 cm → (0,40 + 0,30) ÷ 2 = 0,35 m de diâmetro médio.',why:'O 0,7854 corresponde a π/4 e permite calcular a área circular a partir do diâmetro.',ref:'Manual de Fiscalização do IBAMA/2007, item 1.1.1 (Cubagem de Madeira em Tora — Método Geométrico) e item 1.3.2 (Mourões ou Moirões).'},
 'Madeira serrada — peça a peça':{formula:'V = espessura × largura × comprimento × quantidade',coef:'Sem coeficiente de redução',steps:['Separe peças que tenham as mesmas dimensões.','Meça comprimento, largura e espessura em metros.','Informe quantas peças possuem aquelas mesmas medidas.','O aplicativo multiplica as três dimensões pela quantidade.','Se houver peças de outras dimensões, registre outro grupo; o aplicativo soma os volumes.'],example:'Exemplo: 20 peças de 2,00 m × 0,20 m × 0,03 m → 2,00 × 0,20 × 0,03 × 20.',why:'A peça é medida diretamente; não há estimativa de espaço vazio.',ref:'Manual de Fiscalização do IBAMA/2007, item 1.2.1 (Cubagem de Madeira Serrada nas Diversas Formas).'},
 'Madeira serrada em carga/caminhão':{formula:'Vr = comprimento × largura × altura × 0,70',coef:'Coeficiente 0,70 (70%)',steps:['Meça o comprimento ocupado pela madeira na carga.','Meça a largura ocupada pela madeira.','Meça a altura ocupada pela madeira.','O aplicativo calcula primeiro o volume aparente: comprimento × largura × altura.','Depois multiplica esse volume por 0,70 para estimar o volume real de madeira.'],example:'Exemplo: volume aparente de 10,000 m³ → 10,000 × 0,70 = 7,000 m³ estimados de madeira.',why:'O Manual considera, nesse método, 70% de madeira e 30% de espaços vazios entre as peças.',ref:'Manual de Fiscalização do IBAMA/2007, item 1.2.2 (Cubagem de Madeira Serrada em Caminhão).'},
 'Madeira serrada tabicada / empilhada':{formula:'V = comprimento × largura × (altura − e)',coef:'e = soma das espessuras dos espaços produzidos pelos tabiques/vãos',steps:['Meça comprimento, largura e altura total da pilha.','Identifique os tabiques/sarrafos que produzem espaços vazios na altura.','Some as espessuras desses espaços e informe o total em metros.','O aplicativo subtrai essa soma da altura total.','Depois multiplica comprimento × largura × altura útil.'],example:'Exemplo: pilha com 1,50 m de altura e 0,20 m somados de espaços → altura útil = 1,30 m.',why:'Aqui não se usa desconto percentual fixo; desconta-se o espaço efetivamente produzido pelos tabiques.',ref:'Manual de Fiscalização do IBAMA/2007, item 1.2.3 (Cubagem de Madeira Serrada Empilhada/Armazenada).'},
 'Lenha / escoramento / estaca roliça / acha ou lasca':{formula:'V = comprimento × largura × altura',coef:'Resultado em estéreo (st)',steps:['Considere a pilha formada pelo material.','Meça o comprimento da pilha.','Meça a largura da pilha.','Meça a altura da pilha.','O aplicativo multiplica as três medidas e mantém o resultado em estéreo (st).'],example:'O estéreo inclui os espaços vazios existentes entre as peças da pilha.',why:'O aplicativo não converte automaticamente st para m³ porque não deve presumir um fator de conversão que não tenha sido definido para o caso.',ref:'Manual de Fiscalização do IBAMA/2007, itens 1.2.4 e 1.2.5.'},
 'Dormentes':{formula:'Volume médio da amostra × quantidade total de dormentes',coef:'Amostragem: média de 3 ou mais peças',steps:['Escolha pelo menos 3 dormentes representativos da carga.','Meça comprimento, largura e espessura de CADA dormente escolhido.','Calcule o volume individual de cada um: comprimento × largura × espessura.','Some os volumes individuais e divida pelo número de dormentes medidos. Esse resultado é o VOLUME MÉDIO POR DORMENTE.','Multiplique o volume médio pela quantidade total de dormentes da carga.'],example:'Exemplo: volumes 0,080; 0,085; 0,082 m³ → média = (0,080 + 0,085 + 0,082) ÷ 3 = 0,0823 m³ por dormente. Se houver 100 dormentes: 0,0823 × 100 = 8,230 m³.',why:'A média não é uma medida que o policial deve inventar ou digitar sem cálculo: ela vem das medições de três ou mais peças da amostra.',ref:'Manual de Fiscalização do IBAMA/2007, item 1.3.1 (Dormentes).'},
 'Carvão vegetal':{formula:'V = comprimento × largura × altura',coef:'Resultado em metro de carvão (mdc)',steps:['Meça o comprimento ocupado pela carga de carvão.','Meça a largura.','Meça a altura.','O aplicativo multiplica as três dimensões.','O resultado é apresentado em metro de carvão (mdc).'],example:'As três medidas precisam representar as dimensões da carga considerada na cubagem.',why:'O Manual utiliza essa unidade para a cubagem do carvão vegetal transportado em veículo.',ref:'Manual de Fiscalização do IBAMA/2007, item 1.3.3 (Carvão Vegetal).'}
};
const map={tora:'Madeira em tora / mourão','serrada-peca':'Madeira serrada — peça a peça','serrada-carga':'Madeira serrada em carga/caminhão',tabicada:'Madeira serrada tabicada / empilhada',lenha:'Lenha / escoramento / estaca roliça / acha ou lasca',dormente:'Dormentes',carvao:'Carvão vegetal'};
const steps=m=>`<div style="margin-top:8px"><b>Faça assim:</b><ol style="margin-top:6px">${m.steps.map(x=>`<li>${x}</li>`).join('')}</ol></div><div class="calc-help"><b>Exemplo:</b> ${m.example}</div>`;
function annotate(){const list=document.getElementById('measurementList');if(!list)return;list.querySelectorAll('.measurement-item').forEach(item=>{if(item.querySelector('.cubage-audit'))return;const strong=item.querySelector('.measurement-item-head strong');if(!strong)return;const title=strong.textContent.replace(/^\d+\.\s*/,'').trim(),m=METHODS[title];if(!m)return;const formulaShown=item.querySelector('p')?.textContent||'';const box=document.createElement('div');box.className='legal cubage-audit';box.style.marginTop='10px';box.innerHTML=`<strong>Como este resultado foi obtido</strong><br><b>Regra usada:</b> ${m.formula}<br>${formulaShown?`<b>Números usados na conta:</b> ${formulaShown}<br>`:''}<b>Coeficiente/unidade:</b> ${m.coef}<br><b>Por que:</b> ${m.why}<br><b>De onde saiu:</b> ${m.ref}`;item.appendChild(box);});}
function methodCard(){const form=document.getElementById('measurementForm'),sel=document.getElementById('tipoMadeira');if(!form||!sel)return;const m=METHODS[map[sel.value]];if(!m)return;let box=form.querySelector('.cubage-method-detail');if(!box){box=document.createElement('div');box.className='notice info cubage-method-detail';const button=form.querySelector('button');button?form.insertBefore(box,button):form.appendChild(box);}box.innerHTML=`<strong>Antes de medir — orientação passo a passo</strong>${steps(m)}<hr><b>Fórmula que o aplicativo usará:</b> ${m.formula}<br><b>Coeficiente/unidade:</b> ${m.coef}<br><b>Por que essa regra:</b> ${m.why}<br><b>Fonte:</b> ${m.ref}`;}
function refresh(){setTimeout(()=>{methodCard();annotate()},20)}
document.addEventListener('DOMContentLoaded',()=>{const list=document.getElementById('measurementList'),sel=document.getElementById('tipoMadeira'),next=document.getElementById('nextBtn');if(list)new MutationObserver(annotate).observe(list,{childList:true});if(sel)sel.addEventListener('change',refresh);if(next)next.addEventListener('click',refresh);refresh();});
})();