(()=>{
const METHODS={
 'Madeira em tora / mourão':{formula:'V = 0,7854 × dm² × L × quantidade',coef:'0,7854 = π/4',why:'O Manual adota o método geométrico para obter o volume da tora. O diâmetro médio (dm) é calculado a partir dos diâmetros medidos; mourões seguem o mesmo procedimento.',ref:'Manual de Fiscalização do IBAMA/2007, item 1.1.1 (Cubagem de Madeira em Tora — Método Geométrico) e item 1.3.2 (Mourões ou Moirões).'},
 'Madeira serrada — peça a peça':{formula:'V = espessura × largura × comprimento × quantidade',coef:'Sem coeficiente de redução',why:'Como as peças são medidas individualmente, o volume resulta diretamente das três dimensões da peça, multiplicado pela quantidade de peças iguais.',ref:'Manual de Fiscalização do IBAMA/2007, item 1.2.1 (Cubagem de Madeira Serrada nas Diversas Formas).'},
 'Madeira serrada em carga/caminhão':{formula:'Vr = comprimento × largura × altura × 0,70',coef:'Coeficiente utilizado: 0,70 (70%)',why:'O Manual determina 70% para estimar o volume real da madeira serrada transportada em veículo. Os 30% reduzidos correspondem aos espaços vazios entre uma peça e outra.',ref:'Manual de Fiscalização do IBAMA/2007, item 1.2.2 (Cubagem de Madeira Serrada em Caminhão).'},
 'Madeira serrada tabicada / empilhada':{formula:'V = comprimento × largura × (altura − e)',coef:'e = soma da espessura dos sarrafos/tabiques/vãos',why:'Não se aplica um percentual fixo: o Manual manda medir os espaços vazios produzidos pelos tabiques, somá-los e subtrair esse valor da altura da pilha.',ref:'Manual de Fiscalização do IBAMA/2007, item 1.2.3 (Cubagem de Madeira Serrada Empilhada/Armazenada).'},
 'Lenha / escoramento / estaca roliça / acha ou lasca':{formula:'V = comprimento × largura × altura',coef:'Unidade: estéreo (st); sem coeficiente automático para m³',why:'O estéreo representa o volume da pilha incluindo os vãos decorrentes da forma das peças. O aplicativo mantém o resultado em st para não aplicar automaticamente um fator regional de conversão.',ref:'Manual de Fiscalização do IBAMA/2007, itens 1.2.4 e 1.2.5.'},
 'Dormentes':{formula:'V = comprimento × largura × espessura × quantidade',coef:'Sem coeficiente de redução; regra prática de amostragem',why:'O Manual calcula o volume geométrico da peça. Como regra prática, orienta obter a média do volume de três ou mais peças e multiplicar pela quantidade de dormentes.',ref:'Manual de Fiscalização do IBAMA/2007, item 1.3.1 (Dormentes).'},
 'Carvão vegetal':{formula:'V = comprimento × largura × altura',coef:'Unidade: metro de carvão (mdc)',why:'Para carvão transportado em veículo, o Manual utiliza as dimensões da carga e expressa o resultado em mdc. O mdc é também a unidade indicada pelo Manual para aplicação da multa administrativa.',ref:'Manual de Fiscalização do IBAMA/2007, item 1.3.3 (Carvão Vegetal).'}
};
function annotate(){const list=document.getElementById('measurementList');if(!list)return;list.querySelectorAll('.measurement-item').forEach(item=>{if(item.querySelector('.cubage-audit'))return;const strong=item.querySelector('.measurement-item-head strong');if(!strong)return;const title=strong.textContent.replace(/^\d+\.\s*/,'').trim();const m=METHODS[title];if(!m)return;const formulaShown=[...item.querySelectorAll('p')][0]?.textContent||'';const box=document.createElement('div');box.className='legal cubage-audit';box.style.marginTop='10px';box.innerHTML=`<strong>Memória de cálculo — Manual IBAMA</strong><br><b>Fórmula aplicada:</b> ${m.formula}<br>${formulaShown?`<b>Conta realizada:</b> ${formulaShown}<br>`:''}<b>Coeficiente/unidade:</b> ${m.coef}<br><b>Por que foi utilizado:</b> ${m.why}<br><b>Fonte:</b> ${m.ref}`;item.appendChild(box);});}
function methodCard(){const form=document.getElementById('measurementForm'),sel=document.getElementById('tipoMadeira');if(!form||!sel)return;const map={tora:'Madeira em tora / mourão','serrada-peca':'Madeira serrada — peça a peça','serrada-carga':'Madeira serrada em carga/caminhão',tabicada:'Madeira serrada tabicada / empilhada',lenha:'Lenha / escoramento / estaca roliça / acha ou lasca',dormente:'Dormentes',carvao:'Carvão vegetal'},m=METHODS[map[sel.value]];form.querySelector('.cubage-method-detail')?.remove();if(!m)return;const box=document.createElement('div');box.className='notice info cubage-method-detail';box.innerHTML=`<strong>Como esta cubagem será calculada</strong><br><b>Fórmula:</b> ${m.formula}<br><b>Coeficiente/unidade:</b> ${m.coef}<br><b>Justificativa:</b> ${m.why}<br><b>Origem:</b> ${m.ref}`;form.insertBefore(box,form.querySelector('button'))}
function refresh(){setTimeout(()=>{methodCard();annotate()},0)}
document.addEventListener('DOMContentLoaded',()=>{const list=document.getElementById('measurementList'),form=document.getElementById('measurementForm'),sel=document.getElementById('tipoMadeira');if(list)new MutationObserver(annotate).observe(list,{childList:true,subtree:true});if(form)new MutationObserver(methodCard).observe(form,{childList:true});if(sel)sel.addEventListener('change',refresh);refresh()});
})();