(()=>{
const $=id=>document.getElementById(id),KEY='transporteMadeiraDecisaoV3';
const FIELDS=[
 ['docValido','Documento de controle','O DOF/documento apresentado é válido e autêntico?','Documento inexistente, inválido ou autenticidade não confirmada','GPO 5.6; IN IBAMA 21/2014, art. 48'],
 ['volumeEspecie','Carga física','Volume/quantidade e espécie correspondem ao autorizado?','Quantidade, volume ou espécie em desacordo','GPO 5.6.10.9.1 e 5.6.10.20; IN IBAMA 21/2014, art. 48, I'],
 ['rotaOk','Rota','O percurso constatado corresponde ao autorizado/declarado?','Percurso divergente do autorizado/declarado','GPO 5.6.10.9.2; IN IBAMA 21/2014, art. 48, II'],
 ['veiculoOk','Veículo','Veículo e placas correspondem ao autorizado/declarado?','Veículo, implemento ou placa divergente','GPO 5.6.10.9.3; IN IBAMA 21/2014, art. 48, III'],
 ['validadeOk','Validade','O transporte está dentro do período de validade?','Documento vencido/cancelado ou transporte fora do período','GPO 5.6.10.8 e 5.6.10.9.4; IN IBAMA 21/2014, art. 48, IV'],
 ['produtoOk','Apresentação do produto','A forma física do produto corresponde ao autorizado/declarado?','Apresentação do produto divergente','GPO 5.6.10.9.5; IN IBAMA 21/2014, art. 48, V'],
 ['camposOk','Consistência documental','Documento está sem rasura, omissão ou inconsistência relevante?','Rasura, omissão ou inconsistência relevante','GPO 5.6.10.9.6; IN IBAMA 21/2014, art. 48, VI'],
 ['origemDocOk','Origem','A origem constatada corresponde à informada?','Origem da carga divergente','IN IBAMA 21/2014, art. 48, VII'],
 ['nfOk','DOF × NF × carga','Documento de controle, documento fiscal e carga são compatíveis?','Divergência entre DOF, NF e/ou carga','GPO 5.6.10.10; IN IBAMA 21/2014, art. 48, parágrafo único']
];
let data={};try{data=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('transporteMadeiraDecisaoV2')||'{}')}catch(e){}
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const select=(id,q)=>`<div class="adaptive-check"><label><strong>${q}</strong></label><select id="dec-${id}"><option value="">Não verificado</option><option value="sim">Regular</option><option value="nao">Irregular</option><option value="na">Não foi possível concluir</option></select><div id="detail-${id}" class="adaptive-detail hidden"><label>O que foi constatado?</label><textarea id="txt-${id}" placeholder="Registre somente o fato objetivo constatado, sem conclusão automática."></textarea></div></div>`;
function metrics(){let m=typeof totalM3==='function'?totalM3():0,d=parseFloat($('volumeDeclarado')?.value)||0,p=d&&m?(m-d)/d*100:null;return {m,d,p}}
function irregularities(){return FIELDS.filter(f=>data[f[0]]==='nao').map(f=>({id:f[0],title:f[1],fact:data[`${f[0]}Detail`]||f[3],base:f[4]}))}
function pending(){return FIELDS.filter(f=>!data[f[0]]||data[f[0]]==='na').map(f=>f[1])}
function decision(){const exige=$('exigeDof')?.value,sistema=$('sistema')?.value,r=irregularities(),pend=pending(),{m,d,p}=metrics();if(!exige||exige==='duvida')return {c:'gray',t:'DECISÃO PENDENTE',constatado:'A exigibilidade do documento de controle ainda não foi definida.',caracteriza:'Não é seguro concluir o enquadramento antes de confirmar se o produto está sujeito ao controle.',fazer:'Confirme a exigibilidade ou a hipótese de dispensa e prossiga nas verificações.'};if(exige==='sim'&&sistema==='Nenhum')return {c:'red',t:'IRREGULARIDADE OBJETIVA IDENTIFICADA',constatado:'Produto indicado como sujeito a controle, sem DOF/documento de controle apresentado.',caracteriza:'Em tese, transporte de produto florestal sujeito a controle sem a licença/documento obrigatório.',fazer:'Confirme a natureza do produto e a exigibilidade; caracterizada a situação, adote as providências administrativas e penais indicadas pelo GPO.'};if(r.length)return {c:'red',t:'IRREGULARIDADE(S) OBJETIVA(S) IDENTIFICADA(S)',constatado:r.map(x=>x.fact).join('; ')+'.',caracteriza:'As respostas marcadas como irregulares indicam incompatibilidade documental e/ou física que deve ser individualmente fundamentada.',fazer:'Confira a matriz abaixo, individualize a conduta e registre somente os fatos efetivamente constatados.'};if(pend.length)return {c:'gray',t:'AINDA NÃO É POSSÍVEL CONCLUIR',constatado:`Faltam ${pend.length} conferência(s): ${pend.join(', ')}.`,caracteriza:'Ausência de resposta não significa regularidade.',fazer:'Conclua as verificações pendentes antes de encerrar a fiscalização.'};if(d>0&&m>0&&Math.abs(p)>10)return {c:'yellow',t:'DIVERGÊNCIA DE CUBAGEM — EXIGE CONFIRMAÇÃO',constatado:`Cubagem e documento diferem ${Math.abs(p).toFixed(2).replace('.',',')}%.`,caracteriza:'O percentual, isoladamente, não deve ser convertido em autuação automática. É necessário confirmar método, unidade e desacordo efetivo.',fazer:'Revise a memória de cálculo e confirme se existe incompatibilidade objetiva entre carga e documento.'};if(exige==='nao')return {c:'green',t:'SEM IRREGULARIDADE POR AUSÊNCIA DE DOF',constatado:'Foi indicada hipótese de dispensa e não há outra irregularidade marcada.',caracteriza:'A dispensa deve possuir fundamento aplicável ao produto e à situação concretos.',fazer:'Registre o fundamento da dispensa e verifique infrações independentes.'};return {c:'green',t:'SEM IRREGULARIDADE OBJETIVA IDENTIFICADA',constatado:'Todas as conferências respondidas foram marcadas como regulares.',caracteriza:'Com os dados informados, o motor não identificou incompatibilidade objetiva.',fazer:'Revise o atendimento antes do encerramento; a decisão final permanece do agente.'}}
function matrix(){const r=irregularities();if(!r.length)return '<div class="notice success"><strong>Nenhuma irregularidade específica marcada.</strong></div>';return `<div class="measurement-list">${r.map(x=>`<div class="measurement-item"><strong>${x.title}</strong><p>${x.fact}</p><small>${x.base}</small></div>`).join('')}</div>`}
function fineInfo(){let t=$('tipoMadeira')?.value||'';if(t==='lenha')return 'GPO: valoração por estéreo (st), conforme enquadramento aplicável.';if(t==='carvao')return 'GPO: observar a unidade de valoração aplicável ao carvão (mdc/kg) no caso concreto.';return 'GPO: para madeira, observar a unidade em m³ e a regra específica do enquadramento.'}
function paint(){const x=decision(),r=irregularities(),pend=pending(),result=$('decisionResult');if(!result)return;result.innerHTML=`<div class="decision-traffic ${x.c}"><h3>${x.t}</h3><div class="decision-block"><b>1. O que foi constatado</b><p>${x.constatado}</p></div><div class="decision-block"><b>2. O que isso pode caracterizar</b><p>${x.caracteriza}</p></div><div class="decision-block"><b>3. O que fazer agora</b><p>${x.fazer}</p></div></div>`;$('matrixResult').innerHTML=matrix();$('pendingResult').innerHTML=pend.length?`<div class="notice info"><strong>Antes de concluir, confira:</strong><ul>${pend.map(x=>`<li>${x}</li>`).join('')}</ul></div>`:'';let actions=[];if(x.c==='red'){actions=['<strong>Administrativo:</strong> conferir o enquadramento do item 5.6 do GPO e individualizar a conduta.',`<strong>Valoração:</strong> ${fineInfo()}`,'<strong>Medidas administrativas:</strong> avaliar apreensão e demais providências cabíveis no caso concreto, conforme GPO/Resolução SIMA 05/2021.','<strong>Esfera penal:</strong> avaliar apresentação/comunicação à Polícia Judiciária, em tese art. 46 da Lei 9.605/1998, conforme os fatos.','<strong>Responsáveis:</strong> individualizar a participação do transportador e, quando cabível, emissor/contratante, conforme GPO 5.6.10.19.'];}else actions=['O aplicativo não propõe pacote de sanções sem irregularidade objetiva caracterizada.'];$('actionResult').innerHTML=`<div class="card"><h3>Providências orientativas</h3>${actions.map(a=>`<p>${a}</p>`).join('')}</div>`}
function renderDecision(){const box=$('analysisBox');if(!box)return;box.innerHTML=`<div class="section-title"><h3>Motor de fiscalização adaptativo</h3><span class="status gray">Regular • Irregular • Não verificado</span></div><p class="muted">Responda apenas o que efetivamente conferiu. Marcar “Irregular” abre um campo para registrar o fato objetivo.</p><div class="adaptive-sections"><h3>Documento e carga</h3><div class="grid">${FIELDS.map(f=>select(f[0],f[2])).join('')}</div></div><div id="pendingResult"></div><div id="decisionResult"></div><h3>Matriz de irregularidades</h3><div id="matrixResult"></div><div id="actionResult"></div><details class="legal-details"><summary>Base normativa utilizada pelo motor</summary><div class="legal">GPO 5.6 e 5.6.10; Resolução SIMA nº 05/2021, art. 47 e §1º; Lei 9.605/1998, art. 46; IN IBAMA nº 21/2014, especialmente art. 48; DOF+ conforme regulamentação aplicável. Cubagem técnica e tolerância documental são tratadas separadamente.</div></details>`;FIELDS.forEach(f=>{const id=f[0],el=$(`dec-${id}`),det=$(`detail-${id}`),txt=$(`txt-${id}`);el.value=data[id]||'';txt.value=data[`${id}Detail`]||'';const sync=()=>{det.classList.toggle('hidden',el.value!=='nao');data[id]=el.value;save();paint()};el.onchange=sync;txt.oninput=()=>{data[`${id}Detail`]=txt.value;save();paint()};sync()});paint()}
window.renderAdaptiveDecision=renderDecision;const original=window.renderAnalysis;window.renderAnalysis=function(){if(original)original();renderDecision()};document.addEventListener('DOMContentLoaded',()=>{if($('screen-analysis')?.classList.contains('active'))renderDecision()});
})();