(()=>{
const $=id=>document.getElementById(id);
const KEY='transporteMadeiraDecisaoV1';
const fields=[
 ['docValido','DOF/documento de controle está válido e autêntico?'],
 ['volumeEspecie','Quantidade/volume e espécie correspondem ao autorizado?'],
 ['rotaOk','Percurso corresponde ao autorizado/declarado?'],
 ['veiculoOk','Veículo/placas correspondem ao autorizado/declarado?'],
 ['validadeOk','Transporte está dentro do período de validade?'],
 ['produtoOk','Apresentação do produto corresponde ao autorizado/declarado?'],
 ['camposOk','DOF/documento está sem rasura, omissão ou inconsistência relevante?'],
 ['origemDocOk','Origem da carga corresponde à informada no documento?'],
 ['nfOk','DOF/documento fiscal e carga são compatíveis entre si?']
];
let data={};try{data=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){}
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
function select(id,label){return `<div class="field"><label>${label}</label><select id="dec-${id}"><option value="">Selecione</option><option value="sim">Sim</option><option value="nao">Não</option><option value="na">Não se aplica / não foi possível concluir</option></select></div>`}
function reasons(){let r=[];if(data.docValido==='nao')r.push('documento de controle inexistente, inválido ou sem autenticidade confirmada');if(data.volumeEspecie==='nao')r.push('quantidade/volume ou espécie em desacordo com o autorizado');if(data.rotaOk==='nao')r.push('percurso diferente do autorizado/declarado');if(data.veiculoOk==='nao')r.push('veículo/placas diferentes do autorizado/declarado');if(data.validadeOk==='nao')r.push('documento cancelado, vencido ou transporte fora do período autorizado');if(data.produtoOk==='nao')r.push('apresentação do produto diferente da autorizada/declarada');if(data.camposOk==='nao')r.push('rasura, omissão ou inconsistência no documento');if(data.origemDocOk==='nao')r.push('origem da carga diferente da informada no documento');if(data.nfOk==='nao')r.push('divergência entre documento de controle, documento fiscal e/ou carga');return r}
function decision(){const exige=$('exigeDof')?.value,sistema=$('sistema')?.value,m=typeof totalM3==='function'?totalM3():0,d=parseFloat($('volumeDeclarado')?.value)||0,p=d&&m?(m-d)/d*100:null,r=reasons();if(exige==='nao')return {c:'green',t:'NÃO AUTUAR por falta de DOF',b:'O próprio fluxo indicou hipótese de dispensa. Confirme e registre o fundamento da dispensa; outras irregularidades independentes ainda podem exigir providência.'};if(exige==='sim'&&sistema==='Nenhum')return {c:'red',t:'AUTUAR',b:'Produto sujeito ao controle florestal sendo transportado sem o documento/licença exigível. Base principal: art. 47, §1º, do Decreto 6.514/2008 e art. 46, parágrafo único, da Lei 9.605/1998.'};if(r.length)return {c:'red',t:'AUTUAR — há irregularidade de transporte',b:`Motivo(s) assinalado(s): ${r.join('; ')}. O GPO 5.6.10.9 e o art. 48 da IN IBAMA 21/2014 tratam essas incompatibilidades como causas de invalidade do DOF. O art. 47, §1º, do Decreto 6.514/2008 alcança o transporte sem licença válida ou em desacordo com a obtida. Nas infrações de transporte em que quantidade ou espécie estejam em desacordo, o §3º determina considerar a totalidade do objeto da fiscalização.`};if(d>0&&m>0&&Math.abs(p)>10)return {c:'red',t:'INDÍCIO FORTE PARA AUTUAÇÃO — confirmar enquadramento',b:`A cubagem divergiu ${Math.abs(p).toFixed(2).replace('.',',')}% do volume declarado. A IN IBAMA 21/2014, art. 48, trata divergência de quantidade/volume além dos limites aplicáveis como causa de invalidade. O GPO 5.6.10.20 orienta que, em infração de transporte por quantidade ou espécie em desacordo, a autuação considere a totalidade do objeto. Antes de lavrar, confirme a metodologia de cubagem, a unidade e a regra de tolerância efetivamente aplicável ao produto.`};if(d>0&&m>0&&Math.abs(p)<=10)return {c:'yellow',t:'NÃO AUTUAR AUTOMATICAMENTE só pela cubagem',b:`A diferença calculada é de ${Math.abs(p).toFixed(2).replace('.',',')}%. O art. 53 da IN IBAMA 21/2014 disciplina a divergência de até/mais de 10% no contexto de recebimento pelo consumidor, e não deve ser tratado como franquia universal de transporte. Se todas as demais conferências estiverem regulares, o aplicativo não recomenda autuação exclusivamente com base nesse resultado; o agente deve verificar os limites normativos aplicáveis ao caso concreto.`};return {c:'gray',t:'NÃO É POSSÍVEL CONCLUIR',b:'Complete a cubagem e responda às conferências de regularidade. O aplicativo só indica autuação quando há fato objetivo selecionado que sustente o enquadramento.'}}
function renderDecision(){const box=$('analysisBox');if(!box)return;let old=box.querySelector('#decisionPanel');if(old)old.remove();let wrap=document.createElement('div');wrap.id='decisionPanel';wrap.innerHTML=`<hr><h3>Regularidade para decisão</h3><p class="muted">Marque o resultado da conferência, não apenas se ela foi realizada.</p><div class="grid">${fields.map(x=>select(...x)).join('')}</div><div id="decisionResult"></div><div class="legal"><strong>Base para a decisão</strong><br>Decreto 6.514/2008, art. 47, §§ 1º a 4º; Lei 9.605/1998, art. 46, parágrafo único; IN IBAMA 21/2014, arts. 48 e 53; GPO 5.6.10.9, 5.6.10.10, 5.6.10.19 e 5.6.10.20.</div><div class="notice info"><strong>Regra de segurança:</strong> “AUTUAR” só aparece quando os dados informados apontam irregularidade objetiva. Situações incompletas ou dependentes de interpretação ficam como “confirmar enquadramento”.</div>`;box.appendChild(wrap);fields.forEach(([id])=>{let el=$(`dec-${id}`);el.value=data[id]||'';el.onchange=()=>{data[id]=el.value;save();paint()}});paint()}
function paint(){let x=decision(),el=$('decisionResult');if(!el)return;el.innerHTML=`<div class="notice ${x.c==='red'?'danger':x.c==='green'?'success':'info'}"><h3>${x.t}</h3><p>${x.b}</p></div>`}
const original=window.renderAnalysis||renderAnalysis;window.renderAnalysis=function(){original();renderDecision()};
document.addEventListener('DOMContentLoaded',()=>{if($('screen-analysis')?.classList.contains('active'))renderDecision()});
})();