(()=>{
let deferredPrompt=null;
const $=id=>document.getElementById(id);
const standalone=()=>window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;
const isiOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
function installCard(){if(standalone())return;const start=$('screen-start');if(!start||$('installAppCard'))return;const card=document.createElement('div');card.id='installAppCard';card.className='card install-card no-print';card.innerHTML=`<div class="install-icon">📱</div><div class="install-copy"><h3>Instalar Fiscalização de Madeira</h3><p>Coloque o aplicativo na tela inicial do celular para abrir como um app e ter acesso rápido em campo.</p><div class="btn-row"><button class="btn primary" id="installAppBtn">Instalar aplicativo</button><button class="btn ghost" id="installHelpBtn">Como instalar</button></div><div id="installInstructions" class="install-instructions hidden"></div></div>`;const hero=start.querySelector('.hero');hero?.insertAdjacentElement('afterend',card);$('installAppBtn').onclick=install;$('installHelpBtn').onclick=help;updateButton()}
function updateButton(){const b=$('installAppBtn');if(!b)return;if(deferredPrompt){b.disabled=false;b.textContent='Instalar aplicativo'}else if(isiOS()){b.disabled=false;b.textContent='Adicionar à Tela de Início'}else{b.disabled=false;b.textContent='Ver como instalar'}}
async function install(){if(deferredPrompt){deferredPrompt.prompt();try{await deferredPrompt.userChoice}catch(e){}deferredPrompt=null;updateButton();return}help()}
function help(){const box=$('installInstructions');if(!box)return;box.classList.remove('hidden');if(isiOS())box.innerHTML='<strong>iPhone/iPad</strong><ol><li>Abra este aplicativo no Safari.</li><li>Toque no botão <b>Compartilhar</b>.</li><li>Escolha <b>Adicionar à Tela de Início</b>.</li><li>Confirme em <b>Adicionar</b>.</li></ol>';else box.innerHTML='<strong>Android</strong><ol><li>Abra o aplicativo no Chrome.</li><li>Use o botão <b>Instalar aplicativo</b> quando ele estiver disponível.</li><li>Se o aviso não aparecer, abra o menu do navegador e escolha <b>Instalar app</b> ou <b>Adicionar à tela inicial</b>.</li></ol>'}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installCard();updateButton()});window.addEventListener('appinstalled',()=>{$('installAppCard')?.remove();deferredPrompt=null});document.addEventListener('DOMContentLoaded',()=>{installCard();const p=new URLSearchParams(location.search);if(p.get('action')==='new')setTimeout(()=>{const b=$('freshInspection')||$('newInspectionStart');b?.click()},250);if(p.get('action')==='resume')setTimeout(()=>$('resumeInspection')?.click(),250)});
})();