(()=>{
const $=id=>document.getElementById(id);
const KEY='transporteMadeiraLegalBOv2';
let d={};try{d=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){}
const opts=(id,label,items)=>`<div class="field"><label>${label}</label><select id="bo-${id}"><option value="">Selecione</option>${items.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></div>`;
function inject(){const screen=$('screen-evidence');if(!screen||$('legalBoPanel'))return;const panel=document.createElement('div');panel.id='legalBoPanel';panel.className='card';panel.innerHTML=`<h3>Enquadramento e apoio ao BO/PAmb</h3><p class="muted">Marque somente os fatos confirmados na fiscalização. O aplicativo organiza automaticamente o enquadramento e a minuta orientativa.</p><div class="grid">
${opts('conduta','Conduta constatada',[['transportar','Transportar'],['vender','Vender'],['deposito','Ter em depósito'],['guardar','Guardar'],['destinar','Destinar'],['receber','Receber/adquirir']])}
${opts('situacao','Situação documental',[['sem','Sem licença/DOF exigível'],['invalido','Licença/DOF inválido'],['desacordo','Em desacordo com a licença/DOF'],['regular','Regular']])}
${opts('quantidade','Quantidade/espécie em desacordo?', [['sim','Sim'],['nao','Não'],['duvida','Ainda não conclusivo']])}
${opts('uc','Fato em Unidade de Conservação/Zona de Amortecimento?', [['sim','Sim — conferir art. 70 e plano de manejo'],['nao','Não'],['duvida','Não verificado']])}
${opts('apreensao','Carga apreendida?', [['sim','Sim'],['nao','Não'],['na','Não se aplica / pendente']])}
${opts('veiculo','Veículo apreendido?', [['sim','Sim'],['nao','Não'],['na','Não se aplica / pendente']])}
</div><div id="legalResult"></div><div class="field"><label>Minuta orientativa para histórico do BO/PAmb</label><textarea id="bo-texto" style="min-height:260px"></textarea></div><div class="btn-row no-print"><button id="bo-gerar" class="btn primary">Atualizar minuta</button><button id="bo-copiar" class="btn secondary">Copiar texto</button></div>
<div class="legal"><strong>Base principal</strong><br>Resolução SIMA nº 05/2021, art. 47 e §1º; Decreto Federal nº 6.514/2008, art. 47; Lei Federal nº 9.605/1998, art. 46 e parágrafo único; Código Florestal, art. 36; IN IBAMA nº 21/2014; IN IBAMA nº 16/2022; GPO itens 5.6, 5.6.10 e correlatos. Para nomenclatura/dimensões e rendimento: Resolução CONAMA nº 411/2009 e alterações.</div>`;
screen.appendChild(panel);['conduta','situacao','quantidade','uc','apreensao','veiculo'].forEach(id=>{const e=$(`bo-${id}`);e.value=d[id]||'';e.onchange=()=>{d[id]=e.value;save();build()}});$('bo-gerar').onclick=build;$('bo-copiar').onclick=()=>navigator.clipboard?.writeText($('bo-texto').value).then(()=>alert('Texto copiado.')).catch(()=>{});build();}
const save=()=>localStorage.setItem(KEY,JSON.stringify(d));
function build(){['conduta','situacao','quantidade','uc','apreensao','veiculo'].forEach(id=>d[id]=$(`bo-${id}`)?.value||'');save();const irregular=d.situacao&&d.situacao!=='regular',total=d.quantidade==='sim';let title=irregular?'ENQUADRAMENTO ADMINISTRATIVO INDICADO':'ANÁLISE AINDA NÃO INDICA AUTUAÇÃO';let multa=irregular?'Art. 47, §1º, Resolução SIMA 05/2021 — multa de R$ 300,00 por unidade de medida aplicável.':'';if(total)multa+=' Havendo quantidade ou espécie em desacordo no transporte, considerar a totalidade do objeto vistoriado (GPO 5.6.10.20).';let penal=irregular?'Verificar também o art. 46, parágrafo único, da Lei 9.605/1998 e a providência penal prevista no GPO.':'Sem conclusão penal automática.';let caut=[];if(irregular)caut.push('avaliar apreensão/destinação da carga e demais medidas cabíveis');if(d.uc==='sim')caut.push('verificar incidência do art. 70 da Resolução SIMA 05/2021 e o plano de manejo da UC/Zona de Amortecimento');$('legalResult').innerHTML=`<div class="notice ${irregular?'danger':'info'}"><h3>${title}</h3><p>${multa||'Complete a situação documental e os fatos objetivos.'}</p><p><strong>Responsabilização:</strong> nas irregularidades de transporte, observar o GPO 5.6.10.19 quanto ao transportador pessoa física/jurídica e à empresa emissora do DOF, contratante do frete, conforme participação efetivamente constatada.</p><p><strong>Esfera penal:</strong> ${penal}</p>${caut.length?`<p><strong>Providências a conferir:</strong> ${caut.join('; ')}.</p>`:''}</div>`;
const vol=$('volumeDeclarado')?.value||'[volume declarado]',med=typeof totalM3==='function'?totalM3():0,tipo=$('tipoMadeira')?.selectedOptions?.[0]?.text||'[produto]';let texto=`Durante fiscalização ambiental de transporte de produto florestal, a equipe procedeu à conferência da carga, da documentação apresentada e dos dados constantes do sistema oficial de controle. Foi constatado o transporte de ${tipo}, com volume declarado de ${vol} m³${med?` e volume físico apurado de ${med.toLocaleString('pt-BR',{minimumFractionDigits:3,maximumFractionDigits:3})} m³`:''}.\n\n`;
if(irregular)texto+=`Da conferência, constatou-se que o transporte se encontrava ${d.situacao==='sem'?'sem licença/DOF exigível':d.situacao==='invalido'?'amparado por documento considerado inválido diante das inconsistências verificadas':'em desacordo com a licença/documento de controle obtido'}, circunstância enquadrável, em tese, no artigo 47, §1º, da Resolução SIMA nº 05/2021, sem prejuízo das demais normas aplicáveis. `;else texto+='Até o presente preenchimento, não foi registrada irregularidade documental suficiente para indicar autuação administrativa pelo transporte. ';
if(total)texto+=`Foi constatado desacordo quanto à quantidade e/ou espécie autorizada, razão pela qual, conforme GPO 5.6.10.20, a autuação deve considerar a totalidade do objeto vistoriado. `;
texto+=`Foram confrontados, conforme aplicável, autenticidade e validade do documento, quantidade/volume, espécie, apresentação do produto, veículo/placas, rota, origem/destino e compatibilidade entre DOF/documento de controle, documento fiscal e carga. `;
if(irregular)texto+=`Na esfera administrativa, o enquadramento-base indicado é o artigo 47, §1º, da Resolução SIMA nº 05/2021, observadas a unidade correta, a quantidade objeto da autuação, agravantes e demais regras aplicáveis. ${d.uc==='sim'?'Deverá ser conferida a incidência do artigo 70 da Resolução SIMA nº 05/2021 em razão da Unidade de Conservação/Zona de Amortecimento. ':''}Na esfera penal, deverá ser verificada a incidência do artigo 46, parágrafo único, da Lei nº 9.605/1998, com as providências previstas no GPO. `;
texto+=`Carga apreendida: ${d.apreensao==='sim'?'sim':d.apreensao==='nao'?'não':'a definir/registrar'}. Veículo apreendido: ${d.veiculo==='sim'?'sim':d.veiculo==='nao'?'não':'a definir/registrar'}. As medidas efetivamente adotadas, fotografias, documentos consultados, metodologia de cubagem e memória de cálculo deverão constar do BO/PAmb e anexos.`;$('bo-texto').value=texto;d.texto=texto;save();}
document.addEventListener('DOMContentLoaded',inject);setTimeout(inject,0);
})();